return {
  check = "",
  note = "",
  flame = "",
  debug = "",
  trace = "",
  test = "󰙨",
  lock = "",
  modified = "",
  file = "",
  border = {
    "┌",
    "─",
    "┐",
    "│",
    "┘",
    "─",
    "└",
    "│",
  },
  diagnostics = {
    info = " ",
    hint = " ",
    warn = " ",
    error = " ",
  },
  fold = {
    open = "",
    close = "",
  },
  diff = {
    added = "",
    modified = "",
    removed = "",
  },
  git = {
    added = "",
    modified = "",
    deleted = "",
    renamed = "󰁕",
    untracked = "",
    ignored = "",
    unstaged = "󰄱",
    staged = "",
    conflict = "",
  },
  folder = {
    open = "",
    close = "",
    empty = "󰉖",
  },
  kind = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = "󰉿 ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = "󰉿 ",
    TypeParameter = "󰊄 ",
    Unit = " ",
    Value = "󰉿 ",
    Variable = " ",
  },
}
