return {
  ignore_pattern = { ".git" },
  icons = {
    diagnostics = {
      info = " ",
      hint = " ",
      warn = " ",
      error = " ",
    },
    git = {
      added = "",
      modified = "",
      removed = "",
    },
    kind = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = " ",
      Key = "󰉿 ",
      Keyword = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = " ",
      Number = " ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = " ",
      Text = "󰉿 ",
      TypeParameter = "󰊄 ",
      Unit = " ",
      Value = "󰉿 ",
      Variable = " ",
    },
  },
}
