vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.python3_host_prog = vim.fn.exepath "python3" or vim.fn.exepath "python"

vim.opt.autoindent = true
vim.opt.backspace = { "indent", "eol", "start" }
vim.opt.colorcolumn = "+0"
vim.opt.conceallevel = 0
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.errorbells = false
vim.opt.expandtab = true
vim.opt.exrc = true
vim.opt.fillchars = {
  diff = "╱",
  eob = " ",
  fold = " ",
  foldsep = " ",
  foldopen = "",
  foldclose = "",
}
vim.opt.foldcolumn = "1"
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99
vim.opt.guifont = "JetBrainsMono Nerd Font:h10"
vim.opt.history = 50
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.list = true
vim.opt.listchars = {
  eol = " ",
  tab = "  ",
  extends = "»",
  precedes = "«",
  trail = "•",
}
vim.opt.modeline = false
vim.opt.mousemoveevent = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 1
vim.opt.shiftround = true
vim.opt.shiftwidth = 2
vim.opt.showcmd = false
vim.opt.showmode = false
vim.opt.sidescrolloff = 1
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.smoothscroll = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.undofile = false
vim.opt.updatetime = 300
vim.opt.whichwrap:append "<,>,[,],h,l"
vim.opt.wildmenu = false
vim.opt.wrap = true
vim.opt.writebackup = false
